/* AUTO-GENERATED by scripts/generate-maps.mjs — do not edit */
import { MegIcon, type MegIconProps } from "./meg-icon.js";
import type { MegIconName } from "./icons.generated.js";

export function AcclimationPoint(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"acclimation_point" as MegIconName} title="acclimation point" {...props} />;
}

export function Agent(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"agent" as MegIconName} title="agent" {...props} />;
}

export function Asterism(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"asterism" as MegIconName} title="asterism" {...props} />;
}

export function AuthorityMark(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"authority_mark" as MegIconName} title="authority mark" {...props} />;
}

export function CertitudePoint(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"certitude_point" as MegIconName} title="certitude point" {...props} />;
}

export function Collaboration(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"collaboration" as MegIconName} title="collaboration" {...props} />;
}

export function DoublePoint(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"double_point" as MegIconName} title="double point" {...props} />;
}

export function DoubtPoint(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"doubt_point" as MegIconName} title="doubt point" {...props} />;
}

export function Elray(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"elray" as MegIconName} title="elray" {...props} />;
}

export function ExclamationComma(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"exclamation_comma" as MegIconName} title="exclamation comma" {...props} />;
}

export function Explainability(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"explainability" as MegIconName} title="explainability" {...props} />;
}

export function FriendlyPeriod(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"friendly_period" as MegIconName} title="friendly period" {...props} />;
}

export function Governance(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"governance" as MegIconName} title="governance" {...props} />;
}

export function Hedera(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"hedera" as MegIconName} title="hedera" {...props} />;
}

export function HumanJudgement(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"human_judgement" as MegIconName} title="human judgement" {...props} />;
}

export function Insight(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"insight" as MegIconName} title="insight" {...props} />;
}

export function IronyMark(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"irony_mark" as MegIconName} title="irony mark" {...props} />;
}

export function LovePoint(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"love_point" as MegIconName} title="love point" {...props} />;
}

export function Manicule(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"manicule" as MegIconName} title="manicule" {...props} />;
}

export function PercontationPoint(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"percontation_point" as MegIconName} title="percontation point" {...props} />;
}

export function QuestionComma(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"question_comma" as MegIconName} title="question comma" {...props} />;
}

export function SarMark(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"sar_mark" as MegIconName} title="sar mark" {...props} />;
}

export function SnarkMark(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"snark_mark" as MegIconName} title="snark mark" {...props} />;
}

export function Specification(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={"specification" as MegIconName} title="specification" {...props} />;
}
