import fs from "node:fs";
import path from "node:path";
import {
  ROOT,
  buildFullGlyphAssignment,
  listCanonicalSvgBasenames,
} from "./lib/glyphs.mjs";

const optimizedDir = path.join(ROOT, "assets", "optimized");
const assetsDir = fs.existsSync(optimizedDir) ? optimizedDir : path.join(ROOT, "assets");
const ids = listCanonicalSvgBasenames(assetsDir).map((f) => f.replace(/\.svg$/i, ""));

const resolvedPath = path.join(ROOT, "config", "unicode-map.resolved.json");
const assignment = fs.existsSync(resolvedPath)
  ? JSON.parse(fs.readFileSync(resolvedPath, "utf8"))
  : buildFullGlyphAssignment(ids);

// Filter to known ids only
const glyphs = {};
for (const id of ids) {
  if (assignment[id]) glyphs[id] = assignment[id];
}

// --- parser map ---
const parserOut = path.join(ROOT, "packages", "parser", "src", "glyph-map.generated.ts");
fs.mkdirSync(path.dirname(parserOut), { recursive: true });

const shortcodeEntries = [];
for (const g of Object.values(glyphs)) {
  for (const sc of g.shortcodes) {
    shortcodeEntries.push(
      `  ${JSON.stringify(sc)}: { id: ${JSON.stringify(g.id)}, char: ${JSON.stringify(g.char)}, codepoint: ${JSON.stringify(g.codepoint)} },`,
    );
  }
}

const parserSrc = `/* AUTO-GENERATED by scripts/generate-maps.mjs — do not edit */
export interface GlyphRef {
  id: string;
  char: string;
  codepoint: string;
}

export const GLYPHS_BY_ID: Record<string, GlyphRef> = {
${Object.values(glyphs)
  .map(
    (g) =>
      `  ${JSON.stringify(g.id)}: { id: ${JSON.stringify(g.id)}, char: ${JSON.stringify(g.char)}, codepoint: ${JSON.stringify(g.codepoint)} },`,
  )
  .join("\n")}
};

export const SHORTCODE_MAP: Record<string, GlyphRef> = {
${shortcodeEntries.join("\n")}
};
`;
fs.writeFileSync(parserOut, parserSrc, "utf8");
console.log(`Wrote ${parserOut}`);

// --- SVG package glyphs.json ---
const svgPkgDir = path.join(ROOT, "packages", "svg");
const svgDist = path.join(svgPkgDir, "dist");
fs.mkdirSync(svgDist, { recursive: true });

const glyphsJson = {
  version: "0.0.0",
  glyphs: Object.values(glyphs).map((g) => ({
    id: g.id,
    codepoint: g.codepoint,
    shortcodes: g.shortcodes,
    svg: `${g.id}.svg`,
  })),
};
fs.writeFileSync(
  path.join(svgDist, "glyphs.json"),
  JSON.stringify(glyphsJson, null, 2) + "\n",
  "utf8",
);

// Copy optimized SVGs into package dist
const svgSource = fs.existsSync(optimizedDir) ? optimizedDir : path.join(ROOT, "assets");
for (const id of ids) {
  const src = path.join(svgSource, `${id}.svg`);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(svgDist, `${id}.svg`));
  }
}
console.log(`Wrote SVG package assets to ${svgDist}`);

// --- Framework icon string maps ---
function loadSvgInner(id) {
  const p = path.join(svgSource, `${id}.svg`);
  if (!fs.existsSync(p)) return "";
  const raw = fs.readFileSync(p, "utf8");
  // Keep full svg element for inline use
  return raw.trim();
}

const iconEntries = ids.map((id) => {
  const svg = loadSvgInner(id);
  return `  ${JSON.stringify(id)}: ${JSON.stringify(svg)},`;
});

const iconsTs = `/* AUTO-GENERATED by scripts/generate-maps.mjs — do not edit */
export const ICONS = {
${iconEntries.join("\n")}
} as const;

export type MegIconName = keyof typeof ICONS;
`;

const reactIcons = path.join(ROOT, "packages", "react", "src", "icons.generated.tsx");
fs.mkdirSync(path.dirname(reactIcons), { recursive: true });
fs.writeFileSync(reactIcons, iconsTs, "utf8");

const vueIcons = path.join(ROOT, "packages", "vue", "src", "icons.generated.ts");
fs.mkdirSync(path.dirname(vueIcons), { recursive: true });
fs.writeFileSync(vueIcons, iconsTs, "utf8");

const svelteIcons = path.join(
  ROOT,
  "packages",
  "svelte",
  "src",
  "lib",
  "icons.generated.ts",
);
fs.mkdirSync(path.dirname(svelteIcons), { recursive: true });
fs.writeFileSync(svelteIcons, iconsTs, "utf8");

function toPascal(id) {
  return id
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

const namedReactFixed = `/* AUTO-GENERATED by scripts/generate-maps.mjs — do not edit */
import { MegIcon, type MegIconProps } from "./meg-icon.js";
import type { MegIconName } from "./icons.generated.js";

${ids
  .map((id) => {
    const name = toPascal(id);
    const title = id.replace(/_/g, " ");
    return `export function ${name}(props: Omit<MegIconProps, "name">) {
  return <MegIcon name={${JSON.stringify(id)} as MegIconName} title=${JSON.stringify(title)} {...props} />;
}`;
  })
  .join("\n\n")}
`;

fs.writeFileSync(
  path.join(ROOT, "packages", "react", "src", "named-icons.generated.tsx"),
  namedReactFixed,
  "utf8",
);

// VS Code hover docs from docs/glyphs
const hoverEntries = [];
for (const id of ids) {
  const docPath = path.join(ROOT, "docs", "glyphs", `${id}.json`);
  if (!fs.existsSync(docPath)) continue;
  const doc = JSON.parse(fs.readFileSync(docPath, "utf8"));
  const body = [
    `**${doc.accessibility?.name ?? id}** (\`${doc.codepoint}\`)`,
    "",
    doc.meanings?.engineering ?? "",
    "",
    `LLM: ${doc.ai?.llmInstructions ?? ""}`,
  ].join("\n");
  const shortcodes = glyphs[id]?.shortcodes ?? [`:${id}:`];
  for (const sc of shortcodes) {
    hoverEntries.push(`  ${JSON.stringify(sc)}: ${JSON.stringify(body)},`);
  }
}
const hoverSrc = `/* AUTO-GENERATED by scripts/generate-maps.mjs — do not edit */
export const HOVER_DOCS: Record<string, string> = {
${hoverEntries.join("\n")}
};
`;
fs.writeFileSync(
  path.join(ROOT, "packages", "vscode-ext", "src", "hover-docs.generated.ts"),
  hoverSrc,
  "utf8",
);

console.log("Wrote framework icon maps + named icons + vscode hover docs");
